### PR TITLE
test: use global hook for setup and teardown

### PR DESCRIPTION
**Pull request by marcosvega91**
Hello Matt,

I have updated your code a little bit. I have moved the setup of MSW into `before` and `after` function in a global file. What do you think?

### CODE REVIEW

**Comment by msutkowski** [comment]
> Hello Matt,
> 
> I have updated your code a little bit. I have moved the setup of MSW into `before` and `after` function in a global file. What do you think?

I'll have to check it when I get home in a few hours, but the global hooks will most likely fail in watch mode.

**Comment by msutkowski** [comment]
> > Hello Matt,
> > 
> > I have updated your code a little bit. I have moved the setup of MSW into `before` and `after` function in a global file. What do you think?
> 
> I'll have to check it when I get home in a few hours, but the global hooks will most likely fail in watch mode. 

@marcosvega91 actually, this should work. I think the server instance is still going to be recreated though? Have you tried running this with test:watch?

**Comment by marcosvega91** [comment]
Yes I have tried with with and without it and seems working. The instance server is run one time on every restart. So if I change the code, watch will run my test again closing the previous server and starting a new one

**Comment by msutkowski** [comment]
> Yes I have tried with with and without it and seems working. The instance server is run one time on every restart. So if I change the code, watch will run my test again closing the previous server and starting a new one 

Great! Thanks again for your help! I'll do some more testing where it's running parallel with multiple CPUs as well and if that all works out we're good to go

**Comment by marcosvega91** [comment]
Happy to be useful someway :).

**Pull request merged**
